title: Revista Oficial | Psicología Holokinética
tagline: La revista oficial de Psicología Holokinética. Bimestral.
email: contacto@psicologiaholokinetica.org
description: >-
  La PSICOLOGÍA HOLOKINÉTICA, la psicología científica del 
  siglo XXI, fue iniciada por Rubén Feldman-González influido por la Física Cuántica
  y desde el concepto de Holokinesis, formulado matemáticamente por David Bohm
  en 1986. Esta nueva psicología incorpora la neurología holonómica de Karl Pribram y
  lleva todo esto, con su pertinente epistemología, al campo de la Psicología Científica.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
logo: /assets/img/aiph-logo.png
facebook:
  publisher: https://www.facebook.com/pholokinetica
social:
  name: Psicologia Holokinetica
  links:
    - https://www.facebook.com/pholokinetica
    - https://www.psicologiaholokinetica.org
    - https://www.percepcionunitaria.org
    - http://www.holokinesislibros.com
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
  facebook: 1234

# Build settings
# theme: bulma-clean-theme
remote_theme: Holokinesis-Libros/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-pdf-thumbnail

# General configuration
lang: es
# google_analytics: UA-xxxxxxxx
# comments: false
theme_color: '#3b4ba8'
footer_menu: footer_links
permalink: /revista/:title.html
collections:
  volumenes:
    output: true
favicon: favicon/favicon.ico

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
